import { jsPDF } from "jspdf";
import autoTable from "jspdf-autotable";

const fmtDate = (d) =>
  d
    ? new Date(d).toLocaleDateString("en-LK", { year: "numeric", month: "short", day: "numeric" })
    : "—";

const fmtMoney = (v) =>
  v === null || v === undefined ? "—" : `LKR ${parseFloat(v).toLocaleString()}`;

const workPerformedText = (visit) => {
  const record = visit.service_record;
  if (!record) return "—";
  const parts = [];
  if (record.remarks) parts.push(record.remarks);
  if (record.items?.length)
    parts.push(
      record.items
        .map((i) => `${i.description}${i.quantity > 1 ? ` (x${i.quantity})` : ""}`)
        .join("; "),
    );
  return parts.length ? parts.join(" — ") : "—";
};

const staffText = (visit) => {
  const record = visit.service_record;
  if (!record) return "—";
  const names = (record.assignments ?? []).map((a) => a.staff_name).filter(Boolean);
  if (names.length) return names.join(", ");
  return record.supervisor_name ?? "—";
};

// Vector-based PDF (real text + a real paginated table via jspdf-autotable), unlike the
// screenshot-based exportElementToPdf used for other reports — appropriate here since this
// document is meant to be printed/handed to a customer, where crisp text and clean page
// breaks across a potentially long visit history matter more than 1:1 matching on-screen layout.
export function generateVehicleHistoryPdf({ vehicle, visits, stats, generatedBy }) {
  const doc = new jsPDF({ orientation: "portrait", unit: "mm", format: "a4" });
  const margin = 14;
  let y = margin;

  doc.setFont("helvetica", "bold");
  doc.setFontSize(14);
  doc.text("DriveWell — Vehicle Service Management System", margin, y);
  y += 7;
  doc.setFontSize(11);
  doc.text("Vehicle Service History Report", margin, y);
  y += 9;

  doc.setDrawColor(200);
  doc.line(margin, y, doc.internal.pageSize.getWidth() - margin, y);
  y += 7;

  const vehicleLabel =
    [vehicle.make, vehicle.model].filter(Boolean).join(" ") || "Unregistered make/model";
  doc.setFont("helvetica", "bold");
  doc.setFontSize(10);
  doc.text(
    `${vehicleLabel}${vehicle.year ? ` (${vehicle.year})` : ""} — ${vehicle.plate_no}`,
    margin,
    y,
  );
  y += 6;

  doc.setFont("helvetica", "normal");
  doc.setFontSize(9);
  const ownerLine = vehicle.owner
    ? `Owner: ${vehicle.owner.full_name ?? "—"}  •  ${vehicle.owner.email ?? "—"}${vehicle.owner.phone ? `  •  ${vehicle.owner.phone}` : ""}`
    : "Owner: Unclaimed / no current owner on record";
  doc.text(ownerLine, margin, y);
  y += 8;

  const statLines = [
    `Total visits: ${stats.totalVisits}`,
    `Paid: ${fmtMoney(stats.paidTotal)}   Unpaid: ${fmtMoney(stats.unpaidTotal)}`,
    `Last service: ${fmtDate(stats.lastServiceDate)}`,
    `Next service due at: ${stats.nextServiceOdometer != null ? `${stats.nextServiceOdometer.toLocaleString()} km` : "—"}`,
  ];
  doc.setFont("helvetica", "bold");
  doc.setFontSize(9);
  statLines.forEach((line) => {
    doc.text(line, margin, y);
    y += 5;
  });
  y += 3;

  autoTable(doc, {
    startY: y,
    margin: { left: margin, right: margin },
    head: [["Date", "Package", "Odometer", "Work Performed", "Staff", "Payment", "Total"]],
    body: visits.map((v) => [
      fmtDate(v.service_date),
      v.package_name ?? "—",
      v.service_record?.current_odometer != null
        ? `${v.service_record.current_odometer.toLocaleString()} km`
        : "—",
      workPerformedText(v),
      staffText(v),
      v.invoice?.payment_status ?? "—",
      fmtMoney(v.invoice?.total_amount),
    ]),
    styles: { fontSize: 8, cellPadding: 2, overflow: "linebreak" },
    headStyles: { fillColor: [97, 111, 57], textColor: 255, fontStyle: "bold" },
    columnStyles: {
      0: { cellWidth: 20 },
      2: { cellWidth: 18 },
      3: { cellWidth: "auto" },
      4: { cellWidth: 26 },
      5: { cellWidth: 16 },
      6: { cellWidth: 20 },
    },
    didDrawPage: () => {
      const pageWidth = doc.internal.pageSize.getWidth();
      const pageHeight = doc.internal.pageSize.getHeight();
      doc.setFont("helvetica", "normal");
      doc.setFontSize(7.5);
      doc.setTextColor(120);
      doc.text(
        `Generated by ${generatedBy} on ${new Date().toLocaleString("en-LK")}`,
        margin,
        pageHeight - 8,
      );
      doc.text(`Page ${doc.internal.getNumberOfPages()}`, pageWidth - margin, pageHeight - 8, {
        align: "right",
      });
      doc.setTextColor(0);
    },
  });

  // "Page X of Y" needs the final page count, only known once the table is fully laid out —
  // so the placeholder page number drawn above gets overwritten here with the real total.
  const totalPages = doc.internal.getNumberOfPages();
  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();
  for (let i = 1; i <= totalPages; i++) {
    doc.setPage(i);
    doc.setFillColor(255, 255, 255);
    doc.rect(pageWidth - margin - 22, pageHeight - 12, 22, 6, "F");
    doc.setFont("helvetica", "normal");
    doc.setFontSize(7.5);
    doc.setTextColor(120);
    doc.text(`Page ${i} of ${totalPages}`, pageWidth - margin, pageHeight - 8, { align: "right" });
    doc.setTextColor(0);
  }

  if (visits.length === 0) {
    doc.setFont("helvetica", "normal");
    doc.setFontSize(10);
    doc.text(
      "No service history recorded for this vehicle.",
      margin,
      doc.lastAutoTable.finalY + 10,
    );
  }

  doc.save(`drivewell-service-history-${vehicle.plate_no}.pdf`);
}
