/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as DashboardVolumeRouteImport } from './routes/dashboard/volume'
import { Route as DashboardUsersRouteImport } from './routes/dashboard/users'
import { Route as DashboardScheduleRouteImport } from './routes/dashboard/schedule'
import { Route as DashboardRevenueRouteImport } from './routes/dashboard/revenue'
import { Route as DashboardPerformanceRouteImport } from './routes/dashboard/performance'
import { Route as DashboardPackagesRouteImport } from './routes/dashboard/packages'
import { Route as DashboardBookingsRouteImport } from './routes/dashboard/bookings'
import { Route as DashboardActivityRouteImport } from './routes/dashboard/activity'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardVolumeRoute = DashboardVolumeRouteImport.update({
  id: '/volume',
  path: '/volume',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardUsersRoute = DashboardUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardScheduleRoute = DashboardScheduleRouteImport.update({
  id: '/schedule',
  path: '/schedule',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardRevenueRoute = DashboardRevenueRouteImport.update({
  id: '/revenue',
  path: '/revenue',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardPerformanceRoute = DashboardPerformanceRouteImport.update({
  id: '/performance',
  path: '/performance',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardPackagesRoute = DashboardPackagesRouteImport.update({
  id: '/packages',
  path: '/packages',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardBookingsRoute = DashboardBookingsRouteImport.update({
  id: '/bookings',
  path: '/bookings',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardActivityRoute = DashboardActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => DashboardRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/login': typeof LoginRoute
  '/dashboard/activity': typeof DashboardActivityRoute
  '/dashboard/bookings': typeof DashboardBookingsRoute
  '/dashboard/packages': typeof DashboardPackagesRoute
  '/dashboard/performance': typeof DashboardPerformanceRoute
  '/dashboard/revenue': typeof DashboardRevenueRoute
  '/dashboard/schedule': typeof DashboardScheduleRoute
  '/dashboard/users': typeof DashboardUsersRoute
  '/dashboard/volume': typeof DashboardVolumeRoute
  '/dashboard/': typeof DashboardIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/dashboard/activity': typeof DashboardActivityRoute
  '/dashboard/bookings': typeof DashboardBookingsRoute
  '/dashboard/packages': typeof DashboardPackagesRoute
  '/dashboard/performance': typeof DashboardPerformanceRoute
  '/dashboard/revenue': typeof DashboardRevenueRoute
  '/dashboard/schedule': typeof DashboardScheduleRoute
  '/dashboard/users': typeof DashboardUsersRoute
  '/dashboard/volume': typeof DashboardVolumeRoute
  '/dashboard': typeof DashboardIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/login': typeof LoginRoute
  '/dashboard/activity': typeof DashboardActivityRoute
  '/dashboard/bookings': typeof DashboardBookingsRoute
  '/dashboard/packages': typeof DashboardPackagesRoute
  '/dashboard/performance': typeof DashboardPerformanceRoute
  '/dashboard/revenue': typeof DashboardRevenueRoute
  '/dashboard/schedule': typeof DashboardScheduleRoute
  '/dashboard/users': typeof DashboardUsersRoute
  '/dashboard/volume': typeof DashboardVolumeRoute
  '/dashboard/': typeof DashboardIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/login'
    | '/dashboard/activity'
    | '/dashboard/bookings'
    | '/dashboard/packages'
    | '/dashboard/performance'
    | '/dashboard/revenue'
    | '/dashboard/schedule'
    | '/dashboard/users'
    | '/dashboard/volume'
    | '/dashboard/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/dashboard/activity'
    | '/dashboard/bookings'
    | '/dashboard/packages'
    | '/dashboard/performance'
    | '/dashboard/revenue'
    | '/dashboard/schedule'
    | '/dashboard/users'
    | '/dashboard/volume'
    | '/dashboard'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/login'
    | '/dashboard/activity'
    | '/dashboard/bookings'
    | '/dashboard/packages'
    | '/dashboard/performance'
    | '/dashboard/revenue'
    | '/dashboard/schedule'
    | '/dashboard/users'
    | '/dashboard/volume'
    | '/dashboard/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/volume': {
      id: '/dashboard/volume'
      path: '/volume'
      fullPath: '/dashboard/volume'
      preLoaderRoute: typeof DashboardVolumeRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/users': {
      id: '/dashboard/users'
      path: '/users'
      fullPath: '/dashboard/users'
      preLoaderRoute: typeof DashboardUsersRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/schedule': {
      id: '/dashboard/schedule'
      path: '/schedule'
      fullPath: '/dashboard/schedule'
      preLoaderRoute: typeof DashboardScheduleRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/revenue': {
      id: '/dashboard/revenue'
      path: '/revenue'
      fullPath: '/dashboard/revenue'
      preLoaderRoute: typeof DashboardRevenueRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/performance': {
      id: '/dashboard/performance'
      path: '/performance'
      fullPath: '/dashboard/performance'
      preLoaderRoute: typeof DashboardPerformanceRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/packages': {
      id: '/dashboard/packages'
      path: '/packages'
      fullPath: '/dashboard/packages'
      preLoaderRoute: typeof DashboardPackagesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/bookings': {
      id: '/dashboard/bookings'
      path: '/bookings'
      fullPath: '/dashboard/bookings'
      preLoaderRoute: typeof DashboardBookingsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/activity': {
      id: '/dashboard/activity'
      path: '/activity'
      fullPath: '/dashboard/activity'
      preLoaderRoute: typeof DashboardActivityRouteImport
      parentRoute: typeof DashboardRoute
    }
  }
}

interface DashboardRouteChildren {
  DashboardActivityRoute: typeof DashboardActivityRoute
  DashboardBookingsRoute: typeof DashboardBookingsRoute
  DashboardPackagesRoute: typeof DashboardPackagesRoute
  DashboardPerformanceRoute: typeof DashboardPerformanceRoute
  DashboardRevenueRoute: typeof DashboardRevenueRoute
  DashboardScheduleRoute: typeof DashboardScheduleRoute
  DashboardUsersRoute: typeof DashboardUsersRoute
  DashboardVolumeRoute: typeof DashboardVolumeRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardActivityRoute: DashboardActivityRoute,
  DashboardBookingsRoute: DashboardBookingsRoute,
  DashboardPackagesRoute: DashboardPackagesRoute,
  DashboardPerformanceRoute: DashboardPerformanceRoute,
  DashboardRevenueRoute: DashboardRevenueRoute,
  DashboardScheduleRoute: DashboardScheduleRoute,
  DashboardUsersRoute: DashboardUsersRoute,
  DashboardVolumeRoute: DashboardVolumeRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
